SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE  `users`;

INSERT INTO `users` (`first_name`, `last_name`, `email`, `phone_no`, `password`, `last_login_time`, `role`, `user_type`, `status`, `parent_id`, `created_by`, `updated_by`, `subscription_id`, `communication_type`, `created`, `updated`)VALUES ('Amit', 'Solanki', 'info@securemetasys.com', '(972)609-9884', '453dcc12c14a599d5e6ca8350e5366debb3e9376', '2016-02-12 19:52:52', 'Admin', 'Super', 'active', '0', '0', '0', '', '', '2015-11-10 00:00:00', '2016-02-12 19:52:52');

TRUNCATE TABLE `admin_users`;
TRUNCATE TABLE 	`available_messages`;
TRUNCATE TABLE `activity_report`;
TRUNCATE TABLE `automix_setting`;
TRUNCATE TABLE  `bills_activity_report`;
TRUNCATE TABLE  `bills_count`;
TRUNCATE TABLE  `bills_history`;
TRUNCATE TABLE  `bill_adjustments`;
TRUNCATE TABLE  `coin_inventory`;
TRUNCATE TABLE  `current_teller_transactions`;
TRUNCATE TABLE  `entry_count`;
TRUNCATE TABLE  `error_detail`;
TRUNCATE TABLE  `file_processing_detail`;
TRUNCATE TABLE  `history_report`;
TRUNCATE TABLE  `inventory`;
TRUNCATE TABLE  `manager_log`;
TRUNCATE TABLE  `messages`;
TRUNCATE TABLE  `networking_settings`;
TRUNCATE TABLE  `net_cash_usage_activity_report`;
TRUNCATE TABLE  `teller_activity_report`;
TRUNCATE TABLE  `teller_setup`;
TRUNCATE TABLE  `teller_transaction_total_vault_buys`;
TRUNCATE TABLE  `teller_transaction_vault_buys`;
TRUNCATE TABLE  `teller_user_report`;
TRUNCATE TABLE  `branch_admins`;
TRUNCATE TABLE  `branch_dealers`;
TRUNCATE TABLE  `company_branches`;
TRUNCATE TABLE  `db_growth`;
TRUNCATE TABLE  `dealer_companies`;
TRUNCATE TABLE  `faqs`;
TRUNCATE TABLE  `histories`;
TRUNCATE TABLE  `manager_setup`;
TRUNCATE TABLE  `manager_user_report`;
TRUNCATE TABLE  `side_activity_report`;
TRUNCATE TABLE  `side_log`;
TRUNCATE TABLE  `stations`;
TRUNCATE TABLE  `subscriptions`;
TRUNCATE TABLE  `tickets`;
TRUNCATE TABLE  `transaction_details`;
